var numero1 = 5;
var numero2 = 10;
var numero3 = 5;
var existeNumero = numero1 == numero2;
console.log(existeNumero);
existeNumero = numero1 == numero3;
console.log(existeNumero);
var verdadero = true;
var falso = false;
console.log("Verdadero:", verdadero);
console.log("Falso:", falso);
